### ISSUE TITLE
Find plus results table should not be editable

### ISSUE THREAD

**Issue by halsteadb** [yourhead/pluskit#12]
RW 6.3.8
Stacks - Current version
PlusKit (Registered) 3.0.1

Using FindPlus to search for a word, provides a list of locations found
Tried editing it in right hand column of find plus
RW crashes with a report of "crash on publish to MAMP occurred just after RW generated code (6.3.8)"

MAMP is the HOST
MAMP is not running
MAMP does not need to be running for an edit, only a publish.

Will test and report if also affects RW 7 - YUP, same issue

Secondary and related, I expect that when a FindPlus finds what I am looking for to be able to edit it in Findplus and update the page and/or to be able to double-click the filename and be taken to that page in RapidWeaver to the spot for further editing (Both 6.3.8 and 7.0)

**Comment by yourhead** [comment]
The bug here is that this table view should not be editable. It doesn't really make too much sense.

**Comment by yourhead** [comment]
Fixed in v4.0.1 beta 2
