### ISSUE TITLE
@gdoc does not work with PHP v7

### ISSUE THREAD

**Issue by girlcarew** [yourhead/pluskit#29]
Create a new RW doc.
Add a Styled Text page. 
Add the content "@gdoc((1Ab9n3oYH2JyKJnF9SmpSEgXl5pRJD97j1bMtHTt_l8k))"
(which is for one of my own published google docs).
Change the Filename extension to .php
Add a PlusKit page.
Enable the gdoc option.
Publish under PHP v7. (for me, I have to set this as a MAMP pref)

the gdoc does not publish. But if I revert to PHP 5.6, it works fine.

**Comment by yourhead** [comment]
fixed a long long time ago
