### ISSUE TITLE
PlusKit image light boxing no longer functioning properly in RW8

### ISSUE THREAD

**Issue by yourhead** [yourhead/pluskit#33]
There appear to be some data missing/moved from the export that is causing the PlusKit modifications to fail. Some file names have `.(null)` appended.

**Comment by EricW1970** [comment]
Any news on this one? I have reconfigured to Fancyzoom but that is not as pretty so I hope you can give this issue some love :). Thanks, Eric

**Comment by yourhead** [comment]
I just tested in RW 8.3 (20799) and this appears to be working. I think I fixed this in a previous build but failed to close this bug.
