### ISSUE TITLE
PlusKit refresh loop in rw 6.x Preview

### ISSUE THREAD

**Issue by halsteadb** [yourhead/pluskit#7]
sample project showing the behaviour...

RW 6.3.8
Stacks 3.0.5
PlusKit 3.0.0

[pluskit.rw6.zip](https://github.com/yourhead/pluskit/files/200940/pluskit.rw6.zip)

**Comment by yourhead** [comment]
- only in RW6
- stacks not required
1. new project
2. pluskit page
3. preview page

**Comment by halsteadb** [comment]
Correct, just added a stacks page to have another page to preview.

**Comment by yourhead** [comment]
:+1: 

just taking notes for my future self to read when i'm fixing this in a few days.  you can ignore me.  :-)

**Comment by firedude2894** [comment]
I had this issue as well.
I accidentally previewed the Pluskit page in RW6 and got stuck in a refresh loop.
I've never been on an acid trip, but I think this would be close.

**Comment by yourhead** [comment]
v3.0.1 will flash once as it disables and hides the the pluskit page.
