### ISSUE TITLE
PlusKit Help (?)

### ISSUE THREAD

**Issue by halsteadb** [yourhead/pluskit#8]
PlusKit page selected in edit mode
Question mark on page opens a 5 page support PDF that is out-dated and still associated to LogHound.

Same page, property inspector
Question mark in property inspector does nothing.

**Comment by yourhead** [comment]
Yes. Rewriting documentation for a complex product will take a while.  That's part of our long-term plan.  

I don't think there's a rush. These docs have been out of date for at least 5 years and very few have noticed.  ;-)

**Comment by yourhead** [comment]
@halsteadb -- really really thank you so much for all the testing, by the way.  really appreciated.  !!!   :+1:

**Comment by halsteadb** [comment]
@yourhead My pleasure, anything I can do to help just ask... Brad

**Comment by yourhead** [comment]
The in-app docs are being removed due to the major changes.  so this big is not as pertinent anymore
